# permissions for end users to view authsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernats
    app.kubernetes.io/managed-by: kustomize
  name: authsecret-viewer-role
rules:
- apiGroups:
  - apps.kubernats.ai
  resources:
  - authsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kubernats.ai
  resources:
  - authsecrets/status
  verbs:
  - get
