# permissions for end users to edit consumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernats
    app.kubernetes.io/managed-by: kustomize
  name: consumer-editor-role
rules:
- apiGroups:
  - apps.kubernats.ai
  resources:
  - consumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubernats.ai
  resources:
  - consumers/status
  verbs:
  - get
