---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.kubernats.ai
  resources:
  - authsecrets
  - consumers
  - jetstreams
  - keyvaluestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubernats.ai
  resources:
  - authsecrets/finalizers
  - consumers/finalizers
  - jetstreams/finalizers
  - keyvaluestores/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kubernats.ai
  resources:
  - authsecrets/status
  - consumers/status
  - jetstreams/status
  - keyvaluestores/status
  verbs:
  - get
  - patch
  - update
